config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new' #define the path of url, set signup to replace users/new
  resources :users, except: [:new]#solve error undefined method 'users_path', or type "post 'users', to: 'users#create'"
  #except new means the new html has been assigned to signup
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :tags, except: [:destroy]
  #get 'allComments', to: 'users#list_comment'
  #get 'comments', to: 'comments#new'
  #post 'comments', to: 'comments#create'
  resources :comments

  
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	validates :context, presence:true, length:{minimum:10, maximum:300}
	validates :user_id, presence:true
	validates :article_id, presence:true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :update, :destroy]
	before_action :require_user, except: [:show] 
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def index
		@comments = Comment.where(user_id: current_user).order("updated_at DESC").paginate(page: params[:page], per_page: 4)
	end

	def new
       
	end

	def create
		@comment = Comment.new(comment_params)

		if @comment.save
			flash[:success] = "Comment was successfully created"
			redirect_back(fallback_location: root_path)
		else
			flash[:danger] = "Comment cannot be blank or less than 10 words !"
			redirect_back(fallback_location: root_path)
		end
	end


	def show
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			flash[:success] = "Comment was successfully updated"
			redirect_to comments_path
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		flash[:danger] = "Comment was successfully deleted"
		redirect_back(fallback_location: root_path)
	end

	private
	   def set_comment
	   	 @comment = Comment.find(params[:id])
	   end
	   def comment_params
          params.require(:comment).permit(:context, :user_id, :article_id) 
	   end
	   
	   def require_same_user
	   	  if current_user != @comment.user and !current_user.admin?
	   	  	flash[:danger] = "You are not the owner !"
	   	  	redirect_to root_path
	   	  end
	   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1 align="center">Edit Comment</h1>
<%= render 'sharedElements/errors', object: @comment %>
<%= form_for(@comment, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
	    <div class="col-sm-2 control-label">
	    <%= f.label :context %>
	    </div>
	    <div class="col-sm-8">
	    <%= f.text_field :context, class:"form-control", placeholder:"Comment...", autofocus:true %>
	    </div>
	</div>
	 
	<div class="form-group">
		<div class="col-sm-16 col-sm-offset-5">
	    <%= f.submit "Update Comment", class: 'btn btn-primary btn-m' %>
	    </div>
	</div>
<% end %>

app/views/comments/index.html.erb
<h1 align="center">All Comments Made by <%= current_user.username %></h1>
<div align="center">
	<%= will_paginate %>
	<% @comments.each do |comment| %>
	<ul class="listing">
	   <div class="row">
	      <div class="well col-md-4 col-md-offset-4">
	           <li><h4><%= comment.context %></h4></li>
	           <li>Updated <%= time_ago_in_words(comment.updated_at) %> ago</li>
	           <li>Created at <strong><%= link_to "Here", article_path(comment.article_id) %></strong> on <%= comment.created_at.strftime("%d/%m/%Y") %></li>
	      </div>
	   </div>
	</ul>
	
	<% end %>
	<%= will_paginate %>
</div>