config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new' #define the path of url, set signup to replace users/new
  resources :users, except: [:new]#solve error undefined method 'users_path', or type "post 'users', to: 'users#create'"
  #except new means the new html has been assigned to signup
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :tags, except: [:destroy]
  #get 'allComments', to: 'users#list_comment'
  #get 'comments', to: 'comments#new'
  #post 'comments', to: 'comments#create'
  resources :comments

  
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :article_tags
	has_many :tags, through: :article_tags
	validates :title, presence:true, length:{minimum: 3, maximum: 50}
	validates :description, presence:true, length:{minimum:10, maximum:300}
	validates :user_id, presence:true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	#avoid the problem that get to the edit page by typing the edit url
	before_action :require_user, except: [:index, :show] 
	before_action :require_same_user, only: [:edit, :update, :destroy] #this is a private method, no need to define in application controller
	def index
		#@articles = Article.all
		@articles = Article.paginate(page: params[:page], per_page: 3)
	end

	def new
       @article = Article.new
	end

	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = current_user 
		if @article.save
			#flash[:notice] = "Article was successfully created" change the notice name to fit the bootrape alert style
			flash[:success] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
		#@article = Article.find(params[:id])
		@article_comments = @article.comments.paginate(page: params[:page], per_page: 4)
		@new_comments = @article.comments.new
	end

	def edit
		#@article = Article.find(params[:id])
	end

	def update
		#@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		#@article = Article.find(params[:id])
		@article.destroy
		flash[:danger] = "Article was successfully deleted"
		redirect_to articles_path
	end

	private
	   #reduce redundancy
	   def set_article
	   	 @article = Article.find(params[:id])
	   end
	   #to get the title and des of specific article based on the format of inspect
	   def article_params
          params.require(:article).permit(:title, :description, tag_ids:[])  #[]means the array
	   end

	   def require_same_user
	   	  if current_user != @article.user and !current_user.admin?
	   	  	flash[:danger] = "You are not the owner !"
	   	  	redirect_to root_path
	   	  end
	   end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% object.each do |article| %>
    <div class="row">
    	<div class="col-xs-8 col-xs-offset-2">
    		<div class="well well-lg">
    			<div class="article-title">
    				<%= link_to article.title, article_path(article) %>
    			</div>
    			<div class="article-body">
    				<%= truncate(article.description, length: 100) %>
    				<div class="article-meta-details">
    				<small>Created by: <%= article.user.username %>, <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
    			    </div>
    			</div>
                
                <% if article.tags.any? %>
                   <p>Tags: <%= render article.tags %></p>   
                <% end %>

                <% if login? && (current_user == article.user || current_user.admin?) %>
        			<div class="article-controller">
    					<%= link_to "Edit It", edit_article_path(article), class: "btn btn-s btn-primary" %>
    					<%= link_to "Delete It", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-s btn-danger" %>
                    </div>
                <% end %>
    		</div>
    	</div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<!--define the object to be article when used the errors-->
<%= render 'sharedElements/errors', object: @article %>

<div class="row">
	<div class="col-xs-12">
		<%#= form_for @article do |f| %>
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
		    <div class="col-sm-2 control-label">
		    <%= f.label :title %>
		    </div>
		    <div class="col-sm-8">
		    <%= f.text_field :title, class:"form-control", placeholder:"Title...", autofocus:true %>
		    </div>
		</div>
		 
		 <div class="form-group">
		    <div class="col-sm-2 control-label">
		    <%= f.label :description %>
		    </div>
		    <div class="col-sm-8">
		    <%= f.text_area :description, class:"form-control", placeholder:"Description...", rows:10 %>
		    </div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-8">
			<!--collection_check_boxes(object, collection, value_method, text_method), :id and :name correspond to html id and name-->
		    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
		       <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
		    <% end %>
		    </div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
		    <%= f.submit class: "btn btn-primary btn-lg" %>
		    </div>
		    <!--submit cannot add , before class-->
		</div>
		<% end %>

		<div class="col-sm-4 col-xs-offset-6">
		[ <%= link_to "Cancel", articles_path %> ]
		</div>
	</div>
</div>


app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center"><%= will_paginate %></div>
<%= render 'article', object:@articles %>
<div align="center"><%= will_paginate %></div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<%# if @article.user %> <!--the description of user will deiscard if the article does not have user, but later it will be forced to have one-->
	<ul class="listing">
	   <div class="row center">
	      <div class="col-md-4 col-md-offset-4">
	      	   <li>Created by:</li>
	           <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
	           <li class="user-name"><%= link_to @article.user.username, user_path(@article.user) %></li>
	           <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
	      </div>
	   </div>
	</ul>
	<%# end %>
	<h4 class="center description"><strong>Description: </strong></h4><hr>
	<%= simple_format(@article.description) %>
    <!--rails can automatically find the partial file name (_tag) the same as to the array name (tag) if rendering an array-->
	<% if @article.tags.any? %>
	   <p>Tags: <%= render @article.tags %></p>   
	<% end %>

	<div class="article-controller">

		<% if login? && (current_user == @article.user || current_user.admin?) %>
			<%= link_to "Edit It", edit_article_path(@article), class: "btn btn-s btn-primary" %>
			<%= link_to "Delete It", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-s btn-danger" %>
		<% end %>
        <%= link_to "View All", articles_path,  class: "btn btn-s btn-success" %>
	</div>
    
    <hr>
		<% if @article.comments.any? %>
		   <h4 class="center"><strong>Comments: </strong></h4>
		   	  <% @article_comments.order(updated_at: :desc).each do |c| %>
					<div class="comment-body">
						
						<% if c.user %>
						    
						    	<strong><%= c.user.username %>:</strong> 
						    <small><%= c.context %></small>
						    <br>
						    <small>
						    	Created <%= time_ago_in_words(c.created_at) %> ago
						    </small>

						    <small>
						    	Updated <%= time_ago_in_words(c.updated_at) %> ago
						    </small>

						    <% if login? && (current_user == c.user || current_user.admin?) %>
								<%= link_to "Edit", edit_comment_path(c), class: "btn btn-xs btn-primary" %>
								<%= link_to "Delete", comment_path(c), method: :delete, data: {confirm: "Delete this comment?"}, class: "btn btn-xs btn-danger" %>
						    <% end %>
							
						<% end %>

						
		            </div>
			   <% end %>
			   <div align="center"><%= will_paginate @article_comments %></div>
	          
		<% end %>
    

    <% if login? %>
	    <hr>
		<div class="row">
			<%= render 'sharedElements/errors', object: @new_comments %>
			<%= form_for(@new_comments, :html => {class: "form-horizontal", role: "form"}) do |f| %>
				<div class="form-group">
				    <div class="col-sm-2 control-label">
				    <%= f.label :context %>
				    </div>
				    <div class="col-sm-8">
				    <%= f.text_field :context, class:"form-control", placeholder:"Comment..." %>
				    <%= f.hidden_field :user_id, value:current_user.id %>
				    <%= f.hidden_field :article_id, value:@article.id %>
				    </div>
				</div>
				 
				<div class="form-group">
					<div class="col-sm-16 col-sm-offset-5">
				    <%= f.submit "Create Comment", class: 'btn btn-primary btn-m' %>
				    </div>
				</div>
			<% end %>
		</div>
	<% end %>

</div>
