config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new' #define the path of url, set signup to replace users/new
  resources :users, except: [:new]#solve error undefined method 'users_path', or type "post 'users', to: 'users#create'"
  #except new means the new html has been assigned to signup
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :tags, except: [:destroy]
  #get 'allComments', to: 'users#list_comment'
  #get 'comments', to: 'comments#new'
  #post 'comments', to: 'comments#create'
  resources :comments

  
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :article_tags
	has_many :articles, through: :article_tags
	validates :name, presence:true, uniqueness: true, length:{maximum: 25}
    #validates_uniqueness_of :name
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :set_tag, only: [:show, :edit, :update]
	before_action :require_admin, except: [:index, :show]
	def index
		@tags = Tag.paginate(page: params[:page], per_page: 5)
	end

	def new
		@tag = Tag.new
	end

	def create
		@tag = Tag.new(tag_params)
		if @tag.save
			flash[:success] = "Tag was successfully created"
			redirect_to tags_path
		else
			render 'new'
		end
	end

	def show
		@tag_articles = @tag.articles.paginate(page: params[:page], per_page: 3)
	end

	def edit
	end

	def update
		if @tag.update(tag_params)
			flash[:success] = "Tag was successfully updated"
			redirect_to tag_path(@tag)
		else
			render 'edit'
		end
	end

	private 
	  def set_tag
	  	@tag = Tag.find(params[:id])
	  end

	  def tag_params
	  	params.require(:tag).permit(:name)
	  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= render 'sharedElements/errors', object: @tag %>
<%= form_for(@tag, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
	    <div class="col-sm-2 control-label">
	    <%= f.label :name %>
	    </div>
	    <div class="col-sm-8">
	    <%= f.text_field :name, class:"form-control", placeholder:"Tag Name...", autofocus:true %>
	    </div>
	</div>
	 
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
	    <%= f.submit(@tag.new_record? ? "Create Tag" : "Update Tag", class: 'btn btn-primary btn-lg') %>
	    </div>
	</div>
<% end %>

	<div class="col-sm-4 col-xs-offset-6">
	[ <%= link_to "Cancel", tags_path %> ]
	</div>

app/views/tags/_tag.html.erb
<span class="badge"><%= link_to tag.name, tag_path(tag) %> &nbsp;</span>

app/views/tags/edit.html.erb
<h1 align="center">Edit Tag Name</h1>
<%= render 'form' %>

app/views/tags/index.html.erb
<h1 align="center">All Tags</h1>
<div class="center">
	<%= will_paginate %>
	<% @tags.each do |tag| %>
	   <ul class="listing">
		   <div class="row">
		      <div class="well col-md-4 col-md-offset-4">
		           <li class="tag-name"><%= link_to "#{tag.name}", tag_path(tag) %></li>
		           <li><small><%= pluralize(tag.articles.count, "article") %></small></li>
		      </div>
		   </div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/tags/new.html.erb
<h1 align="center">Create Tag</h1>
<%= render 'form' %>

app/views/tags/show.html.erb
<h1 align="center"><%= "Tag: " + @tag.name %></h1>
<div align="center">
	<% if login? and current_user.admin? %>
	<div class="row">
		<span class="badge", style="font-size: 15px">
		<%= link_to "Edit Tag Name", edit_tag_path(@tag) %>
	    </span>
    </div>
    <% end %>
	<%= will_paginate @tag_articles %>
</div>
<%= render 'articles/article', object:@tag_articles %>
<div align="center">
	<%= will_paginate @tag_articles %>
</div>