config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new' #define the path of url, set signup to replace users/new
  resources :users, except: [:new]#solve error undefined method 'users_path', or type "post 'users', to: 'users#create'"
  #except new means the new html has been assigned to signup
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :tags, except: [:destroy]
  #get 'allComments', to: 'users#list_comment'
  #get 'comments', to: 'comments#new'
  #post 'comments', to: 'comments#create'
  resources :comments

  
end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; Designed by Eagle
		</small>
		<nav>
			<ul>
				<li><%= link_to "FAKE FOOTER", "#" %></li>
				<li><%= link_to "FAKE FOOTER", "#" %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |notice, msg| %>
		<div class='alert alert-<%= "#{notice}" %>' id="msg_box">
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<ul><li style="list-style: none"><%= msg %></li></ul>
		</div>
		<% end %>
	</div>
</div>



app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">FURNO</a>-->
      <%= link_to "FURNO", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "All Users", users_path %></li>
        <% if login? %>
          <li><%= link_to "All Comments", comments_path %></li>
        <% end %>

        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tags<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Tags", tags_path %></li>
            <li role="separator" class="divider"></li>
            <% Tag.all.each do |tag| %>
                <li><%= link_to "#{tag.name}", tag_path(tag) %></li>
            <% end %>
          </ul>
        </li>
        
        <% if login? %>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "New Article", new_article_path %></li>
                    <% if current_user.admin? %>
                      <li><%= link_to "New Tag", new_tag_path %></li>
                    <% end %>
                    
                  </ul>
            </li>
        <% end %>

      </ul>
      
     

      <ul class="nav navbar-nav navbar-right">
        <% if login? %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li style="padding-left: 20px"><%= current_user.admin? ? "Admininistrator" : "Ordinary User" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furno</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>